image: node:latest

cache:
  paths:
  - node_modules/

job:
  script:
  - apt-get update -qy
  - apt-get install -y ruby ruby-dev rubygems-integration
  - npm install
  - worker: node bot.js
  - gem install --no-rdoc --no-ri dpl
  - dpl --provider=heroku --app=spacediscord-anime-bot --api-key=374a5f45-339f-4e03-a3af-6418c93c8a8a
# change app name and api key if necessary
